security:
    encoders:
        App\Domain\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\UserInterface: plaintext

    role_hierarchy:
        ROLE_COMPANY:   [ROLE_USER, ROLE_SELF_USER]

    providers:
        chain_provider:
            chain:
                providers: [user_provider, company_provider]
        user_provider:
            entity:
                class: App\Domain\Entity\User
                property: username
        company_provider:
            memory:
                users:
                    Bilemo:  { password: 'Bilemo', roles: [ 'ROLE_COMPANY' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|try)/
            security: false
        doc:
            pattern: ^/api/doc
            security: false
        user_login:
            pattern: ^/api/user/token
            provider: user_provider
            stateless: true
            anonymous: ~
            json_login:
                check_path:               user_token
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        company_login:
            pattern: ^/api/company/token
            provider: company_provider
            stateless: true
            anonymous: ~
            json_login:
                check_path:               company_token
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        main:
            pattern: ^/
            provider: chain_provider
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator

    access_control:
        - { path: ^/api/user/token,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/company/token,  roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/phone/,        roles: ROLE_USER,     methods: [GET] }
        - { path: ^/api/phone/,        roles: ROLE_COMPANY,  methods: [PUT, DELETE] }
        - { path: ^/api/phone,          roles: ROLE_USER,     methods: [GET] }
        - { path: ^/api/phone,          roles: ROLE_COMPANY,  methods: [POST] }

        - { path: ^/api/user/,         roles: ROLE_SELF_USER, methods: [GET] }
        - { path: ^/api/user/,         roles: ROLE_COMPANY, methods: [PUT, DELETE] }
        - { path: ^/api/user,           roles: ROLE_COMPANY,  methods: [GET, POST] }
