security:
    encoders:
        App\Domain\Entity\Client:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\UserInterface: plaintext

    role_hierarchy:
        ROLE_COMPANY:   [ROLE_CLIENT, ROLE_SELF_CLIENT]

    providers:
        chain_provider:
            chain:
                providers: [client_provider, company_provider]
        client_provider:
            entity:
                class: App\Domain\Entity\Client
                property: username
        company_provider:
            memory:
                users:
                    Bilemo:  { password: 'Bilemo', roles: [ 'ROLE_COMPANY' ] }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|try)/
            security: false
        doc:
            pattern: ^/api/doc
            security: false
        client_login:
            pattern: ^/api/token/client
            provider: client_provider
            stateless: true
            anonymous: ~
            json_login:
                check_path:               client_token
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        company_login:
            pattern: ^/api/token/company
            provider: company_provider
            anonymous: ~
            json_login:
                check_path:               company_token
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        main:
            pattern: ^/api
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator

    access_control:
        - { path: ^/api/client/token,   roles: IS_AUTHENTICATED_ANONYMOUSLY,  methods: POST }
        - { path: ^/api/company/token,  roles: IS_AUTHENTICATED_ANONYMOUSLY,  methods: POST }

        - { path: ^/api/phones/,        roles: ROLE_CLIENT,                   methods: [GET] }
        - { path: ^/api/phones/,        roles: ROLE_COMPANY,                  methods: [PUT, DELETE] }
        - { path: ^/api/phones,         roles: ROLE_CLIENT,                   methods: [GET] }
        - { path: ^/api/phones,         roles: ROLE_COMPANY,                  methods: [POST] }

        - { path: ^/api/clients/,       roles: ROLE_SELF_CLIENT,              methods: [GET, PUT, DELETE] }
        - { path: ^/api/clients,        roles: ROLE_COMPANY,                  methods: [GET, POST] }
