App\Domain\Entity\User:
    attributes:
        username:
            groups: ['users_list', 'user']
        email:
            groups: ['users_list', 'user']
        createdAt:
            groups: ['users_list']
