App\App\Pagination\PaginatedCollection:
    attributes:
        total:
            groups: ['phones_list', 'users_list']
        limit:
            groups: ['phones_list', 'users_list']
        _links:
            groups: ['phones_list', 'users_list']
        objects:
            groups: ['phones_list', 'users_list']
