App\Domain\Entity\Phone:
    attributes:
        createdAt:
            groups: ['phone']
        brand:
            groups: ['phone_list', 'phone']
        model:
            groups: ['phone_list', 'phone']
        description:
            groups: ['phone_list', 'phone']
        price:
            groups: ['phone']
        stock:
            groups: ['phone']
