App\Domain\Entity\Address:
    attributes:
        streetAddress:
            groups: ['user']
        city:
            groups: ['users_list', 'users_client_list', 'user']
        postcode:
            groups: ['users_list', 'users_client_list', 'user']
