App\Domain\Entity\User:
    attributes:
        username:
            groups: ['user_list', 'user']
        email:
            groups: ['user_list', 'user']
        createdAt:
            groups: ['user_list']
        phoneNumber:
            groups: ['user_list']