App\Domain\Entity\Client:
    attributes:
        username:
            groups: ['clients_list', 'client', 'users_client_list', 'user']
        email:
            groups: ['clients_list', 'client']
        phoneNumber:
            groups: ['client']
        createdAt:
            groups: ['clients_list', 'client']
        users:
            groups: ['client']
