parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    doctrine_migrations:
        resource: '%kernel.root_dir%/Domain/Migrations'
        namespace: 'App\Domain\Migrations\'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

    App\App\EventListener\ApiExceptionSubscriber:
        arguments:
            $isAppDebug: '%kernel.debug%'

    app.security.jwt_token_authenticator:
        class: App\App\Security\JwtTokenAuthenticator
#        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
#        public: true
#        autowire: true
#        autoconfigure: false