parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    doctrine_migrations:
        resource: '%kernel.root_dir%/Domain/Migrations'
        namespace: 'App\Domain\Migrations\'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\UI\Action\:
        resource: '../src/UI/Action'
        tags: ['controller.service_arguments']

    App\App\EventSubscriber\ApiExceptionSubscriber:
        arguments:
            $isAppDebug: '%kernel.debug%'

    App\App\Pagination\PaginationFactory:
        arguments:
            $itemsPerPage: 10

